### ISSUE TITLE
Problems trying to install with maven

### ISSUE THREAD

**Issue by thefrogline** [unnamed/CommandFlow#12]
Hello! I really liked your command manager, and I wanted to try to use it, but when I want to use it with maven I get several errors, I have everything set, as the read.me says, the library is still running or something I'm doing wrong ?, I await your answer, thanks for reading
![image](https://user-images.githubusercontent.com/76601496/119248939-573d0680-bb5a-11eb-96b2-5bbfd58a3697.png)
![image](https://user-images.githubusercontent.com/76601496/119248943-5dcb7e00-bb5a-11eb-81f4-bc8f6f2f2551.png)
![image](https://user-images.githubusercontent.com/76601496/119248948-66bc4f80-bb5a-11eb-9275-ecf96c9648e9.png)
![image](https://user-images.githubusercontent.com/76601496/119248981-b00c9f00-bb5a-11eb-9daf-e2df110b2cc1.png)

**Comment by pixeldev** [comment]
Many of times we forget to update the versions of our libraries at the README.md.
You can check out our nexus repository where u can get the most recent version of any of our libraries.
Use the link below: https://repo.unnamed.team/#browse/browse

Currently the latest version of CommandFlow is **'0.4.0'** using the repository **'https://repo.unnamed.team/repository/unnamed-releases/'**

Hope this solution works.

Cheers.

**Comment by thefrogline** [comment]
![image](https://user-images.githubusercontent.com/76601496/119249543-e77d4a80-bb5e-11eb-8d30-2b9807a10829.png)
Yes it worked for me, thank you very much! and also thanks for responding quickly
