### ISSUE TITLE
Wiki or enhanced README

### ISSUE THREAD

**Issue by Paul2708** [unnamed/CommandFlow#9]
Hey,
this repo seems to be a nice framework.
Could you provide the concept or some general usage examples?

Greetings
Paul

**Comment by FixedDev** [comment]
One of the days I'm going to create an enhanced readme with some example usage. Later on the wiki will be added

**Comment by dustinlacewell** [comment]
Really anticipating some example usages of this exciting library!

**Comment by FixedDev** [comment]
Some examples are provided in the Examples module now, the Examples module will be expanded with time to provide more examples of usage for CommandFlow.
